// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KrS_sEB6zLV2LccYAg5PnbhkBGHL8lo',
    appId: '1:71452640804:web:230080f0ab5d4be1e1bab1',
    messagingSenderId: '71452640804',
    projectId: 'appnotebuy',
    authDomain: 'appnotebuy.firebaseapp.com',
    storageBucket: 'appnotebuy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIDHCGdypnltCGBOeAj-6VEjQElpK_vY',
    appId: '1:71452640804:android:441fa65be881f409e1bab1',
    messagingSenderId: '71452640804',
    projectId: 'appnotebuy',
    storageBucket: 'appnotebuy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY2OLQPlJKfzdD5mQgJJ9dP1yNiMMafwg',
    appId: '1:71452640804:ios:377e86997903903be1bab1',
    messagingSenderId: '71452640804',
    projectId: 'appnotebuy',
    storageBucket: 'appnotebuy.firebasestorage.app',
    iosBundleId: 'com.example.ghiNo',
  );
}
